config/routes.rb
AplicacionMedica::Application.routes.draw do

  devise_for :users,:controllers => { :registrations =>'registration', :passwords => "password"} 
  
  root :controller => 'home', :action => :index
  get 'about',   to: 'home#about',  as: 'about' 
  get 'account_created' => 'home#account_created'
  get 'password_reset' => 'home#password_reset'
  get 'password_reseted' => 'home#password_reseted'
  post '/enviar_correo_contacto', to: 'home#enviarCorreoContacto'

  get '/antecedentes/index', to: 'antecedentes#index', :as => :antecedentes_index 
  post '/antecedentes/:id', to: 'antecedentes#edit'
  post '/editar_alergia', to: 'antecedentes#editarAlergia'
  post '/agregar_alergia', to: 'antecedentes#agregarAlergia'
  post '/guardar_antecedentes_sociales', to: 'antecedentes#guardarAntecedentesSociales'
  post '/cargar_antecedentes', to: 'antecedentes#cargarAntecedentes'
  post '/guardar_antecedente_familiar_muerte', to: 'antecedentes#guardarAntecedenteFamiliarMuerte'
  post '/guardar_antecedente_familiar_cronica', to: 'antecedentes#guardarAntecedenteFamiliarCronica'
  post '/guardar_antecedentes_ginecologicos', to: 'antecedentes#guardarAntecedentesGinecologicos'

  get '/ocupaciones/new', to: 'ocupaciones#new', :as => :ocupaciones_new
  post '/ocupaciones', to: 'ocupaciones#create'
  get '/ocupaciones/index', to: 'ocupaciones#index', :as => :ocupaciones_index  
  get '/ocupaciones/:id', to: 'ocupaciones#edit'
  post '/cargar_ocupaciones', to: 'ocupaciones#cargarOcupaciones'

  get '/habitos_alcohol/new', to: 'habitos_alcohol#new', :as => :habitos_alcohol_new
  post '/habitos_alcohol', to: 'habitos_alcohol#create'   
  get '/habitos_alcohol/index', to: 'habitos_alcohol#index', :as => :habitos_alcohol_index  
  get '/habitos_alcohol/:id', to: 'habitos_alcohol#show'
  post '/guardar_habito_alcohol_resumen', to: 'habitos_alcohol#guardarHabitoAlcoholResumen'  

  get '/habitos_tabaco/new', to: 'habitos_tabaco#new', :as => :habitos_tabaco_new
  post '/habitos_tabaco', to: 'habitos_tabaco#create'   
  get '/habitos_tabaco/index', to: 'habitos_tabaco#index', :as => :habitos_tabaco_index  
  get '/habitos_tabaco/:id', to: 'habitos_tabaco#edit'

  get '/vacunas/index', to: 'vacunas#index', :as => :vacunas_index
  get '/vacunas/calendario', to: 'vacunas#calendario', :as => :vacunas_calendario 
  get '/vacunas/otras_vacunas', to: 'vacunas#otras_vacunas', :as => :otras_vacunas
  post '/actualizar_vacunas', to: 'vacunas#actualizar'
  
  post '/bloquear_hora', to: 'agendamiento#bloquearHora', :as => :bloquearHora
  post '/desbloquear_hora', to: 'agendamiento#desbloquearHora', :as => :desbloquearHora

  post '/guardar_actividad_fisica', to: 'antecedentes#guardarActividadFisica'
  post '/guardar_actividad_fisica_resumen', to: 'antecedentes#guardarActividadFisicaResumen'  

  resources :atenciones_salud
  post '/agregar_prestacion', to: 'persona_prestacion#agregarPrestacion', :as => :agregarExamen
  post '/agregar_prestacion_ant', to: 'persona_prestacion#agregarPrestacionAntecedentes'
  post '/eliminar_prestacion', to: 'persona_prestacion#eliminarPrestacion', :as => :eliminarPrestacion
  post '/agregar_diagnostico', to: 'persona_diagnostico#agregarDiagnostico', :as => :agregarDiagnostico
  post '/agregar_diagnostico_ant', to: 'persona_diagnostico#agregarDiagnosticoAntecedentes'
  post '/crear_atencion', to: 'atenciones_salud#crearAtencion'
  get '/sin_permiso', to: 'atenciones_salud#sinPermiso'
  get '/sin_editar', to: 'atenciones_salud#sinEditar'
  post '/reabrir_atencion', to: 'atenciones_salud#reabrirAtencion'
  post '/ver_atencion', to: 'atenciones_salud#verAtencion'
  post '/editar_atencion', to: 'atenciones_salud#editarAtencion'
  post '/cargar_diagnosticos', to: 'persona_diagnostico#cargarDiagnosticos'
  post '/agregar_persona_notificacion', to: 'persona_diagnostico#agregarPersonaNotificacion'
  post '/agregar_persona', to: 'persona#agregarPersona'
  post '/cargar_cercanos', to: 'persona#cargarCercanos'
  post '/agregar_info_interconsulta', to: 'persona_diagnostico#agregarInfoInterconsulta'
  post '/agregar_info_eno', to: 'persona_diagnostico#agregarInfoEno'
  post '/agregar_info_prestacion', to: 'persona_prestacion#agregarInfoPrestacion'  
  post '/cargar_prestaciones', to: 'persona_prestacion#cargarPrestaciones'
  post '/eliminar_diagnostico', to: 'persona_diagnostico#eliminarDiagnostico'
  post '/guardar_diagnostico', to: 'persona_diagnostico#guardarDiagnostico', :as => :guardarDiagnostico 
  post '/cargar_medicamentos', to: 'persona_medicamento#cargarMedicamentos'
  post '/agregar_medicamento', to: 'persona_medicamento#agregarMedicamento'
  post '/agregar_medicamento_ant', to: 'persona_medicamento#agregarMedicamentoAntecedentes'
  post '/eliminar_medicamento', to: 'persona_medicamento#eliminarMedicamento'
  post '/guardar_medicamento', to: 'persona_medicamento#guardarMedicamento'
  post '/guardar_metricas', to: 'persona_metricas#guardarMetricas'
  post '/cargar_datos_metricas', to: 'persona_metricas#cargarDatosMetricas'
  post '/guardar_texto', to: 'atenciones_salud#guardarTexto'
  post '/autoguardar_comentario', to: 'persona_diagnostico#autoguardarComentario'
  post '/descargar_constancia_ges', to: 'persona_diagnostico#descargarConstanciaGes'
  post '/descargar_interconsulta', to: 'persona_diagnostico#descargarInterconsulta'
  post '/descargar_notificacion_obligatoria', to: 'persona_diagnostico#descargarNotificacionObligatoria'
  post '/descargar_certificado', to: 'atenciones_salud#descargarCertificado'
  post '/descargar_indicaciones', to: 'atenciones_salud#descargarIndicaciones'
  post '/descargar_receta', to: 'atenciones_salud#descargarReceta'
  post '/persona_prestacion/index_examen', to: 'persona_prestacion#indexExamen', :as => :persona_prestacion_index_examen  
  get '/persona_prestacion/index_examen', to: 'persona_prestacion#indexExamen'
  post '/persona_prestacion/index_procedimiento', to: 'persona_prestacion#indexProc', :as => :persona_prestacion_index_procedimiento  
  get '/persona_prestacion/index_procedimiento', to: 'persona_prestacion#indexProc'
  post '/agregar_diag_med', to: 'persona_medicamento#agregarDiagMed'
  post '/agregar_diag_cert', to: 'atenciones_salud#agregarDiagCert'
  post '/agregar_diag_pres', to: 'persona_prestacion#agregarDiagPres'
  post '/agregar_pres_int', to: 'persona_diagnostico#agregarPresInt'
  post '/actualizar_diag_med', to: 'persona_medicamento#actualizarDiagMed'
  post '/guardar_atencion', to: 'atenciones_salud#update'
  post '/cargar_atenciones_salud', to: 'atenciones_salud#cargarAtenciones'
  post '/cargar_atenciones_salud_para_pago', to: 'atenciones_salud#cargarAtencionesParaPago'
  post '/agregar_info_certificado', to: 'atenciones_salud#agregarInfoCertificado'
  post '/actualizar_diag_certificado', to: 'atenciones_salud#actualizarDiagCertificado'
  post '/actualizar_diag_prestacion', to: 'persona_prestacion#actualizarDiagPrestacion'
  post '/actualizar_diag_prestacion_int', to: 'persona_prestacion#actualizarDiagPrestacionInt'
  
  post '/agendamiento/agregarHora', to: 'agendamiento#new'
  get '/agendamiento/buscarHora', to: 'agendamiento#showFormBusqueda', :as => :agendaShowFormBusqueda
  get '/agendamiento/generarHora/:especialidad_id/:prestador_id/:profesional_id', to: 'agendamiento#generarHora'
  put '/agendamiento/generarHora', to: 'agendamiento#generarHora', :as => :generarHora #Esta es solo para ponerle un nombre a la anterior pero sin parámetros
  get '/agendamiento/buscadorHora', to: 'agendamiento#buscadorHora', :as => :agendamientoBuscadorHora
  post '/cargarTodos', to: 'agendamiento#cargarTodos', :as => :agendamientoCargarTodos
  post '/filtrar_profesionales', to: 'agendamiento#filtrarProfesionales', :as => :filtrarProfesionales
  post '/filtrar_especialidad', to: 'agendamiento#filtrarEspecialidad'
  post '/buscar_horas', to: 'agendamiento#buscarHoras', :as => :buscarHoras
  post '/buscar_horas_profesional', to: 'agendamiento#buscarHorasProfesional'
  post '/aux/formNuevaHora', to: 'agendamiento#agregarNuevaHora', :as => :agregarHora
  post '/aux/mostrarEventos', to: 'agendamiento#mostrarEventos', :as => :showEventos
  post '/aux/detalleEvento', to: 'agendamiento#detalleEvento', :as => :detalleEvento
  post '/modificar_evento', to: 'agendamiento#modificarEvento'
  post '/aux/pedirHoraEvento', to: 'agendamiento#pedirHoraEvento', :as => :pedirHoraEvento
  post '/aux/cancelarHora', to: 'agendamiento#cancelarHora', :as => :cancelarHora
  post '/eliminarHora', to: 'agendamiento#eliminarHora'
  post '/aux/confirmarHora', to: 'agendamiento#confirmarHora', :as => :confirmarHora
  post '/aux/marcarLlegada', to: 'agendamiento#marcarLlegada', :as => :marcarLlegada
  post '/aux/buscarHoraFormActualizar', to:'agendamiento#showFormBusquedaActualizar', :as => :agendaShowFormBusquedaRefresh
  post '/preparar_ingreso', to: 'agendamiento#prepararIngreso'
  post '/cargar_cancelar_accion', to: 'agendamiento#cargarCancelarAccion'
  post '/cargar_vista_sin_cancelar', to: 'agendamiento#cargarVistaSinCancelar'
  post '/cancelar_accion_masiva', to: 'agendamiento#cancelarAccionMasiva'
  post '/cargar_pacientes', to: 'agendamiento#cargarPacientes'

  post '/actualizar_atenciones', to: 'home#actualizarAtenciones'
  post '/revisar_actualizaciones', to: 'home#revisarActualizaciones'

  post '/generar_boletas', to: 'administracion#generarBoletas'
  post '/filtrar_boletas', to: 'administracion#filtrarBoletas'
  post '/cargar_atenciones_boleta', to: 'administracion#cargarAtencionesBoleta'
  post '/anular_boleta', to: 'administracion#anularBoleta'

end

app/helpers/home_helper.rb
module HomeHelper
	def getPersona(id)
		@persona = PerPersonas.find(id)
		return @persona.showName('%n%p%m') 
	end
end

app/views/home/_horas_agendadas.html.erb
<div id="horas-agendadas">
  <h4>Horas agendadas para el día</h4>
  <% if @agendamientos.empty? %>
    No hay horas agendadas para hoy.
  <% else %>

  <table class="table table-striped table-hover table-condensed">
    <thead class="ajust-head">
      <tr class="info" ><th class="col-sm-1">Hora</th><th class="col-sm-3">Paciente</th><th class="col-sm-1">Rut</th><th class="col-sm-2">Estado</th><th class="col-sm-1">Llegada</th><th class="col-sm-2">Atención</th></tr>
    </thead>
    <tbody>
    <% @agendamientos.each do |agendamiento| %>
      <tr>
        <td><%= agendamiento.fecha_comienzo.to_s(:time) %></td> 
        <% if agendamiento.persona %>
          <td>
            <%= agendamiento.persona.showName('%n%p%m') %>
          </td>
          <td>
            <%= agendamiento.persona.showRut %>
          </td>   
          <% else %>
          <td colspan='2'>
            No agendada.
          </td>  
        <% end %>                 
        <td><%= agendamiento.estado.nombre %></td>
        <td>
          <% if  agendamiento.fecha_llegada_paciente %>
            <%= agendamiento.fecha_llegada_paciente.to_s(:time) %>
          <% else %>
            - 
          <% end %>
        </td>                
        <td>
          <% if agendamiento.estado_id == 7 %>
            <%= button_to "Ver", {:controller => :atenciones_salud, :action => 'verAtencion', :id_atencion => agendamiento.atencion_salud.id }, :method => :post,class: "btn btn-xs btn-info" %><%= button_to "Reabrir", {:controller => :atenciones_salud, :action => 'reabrirAtencion', :id_atencion => agendamiento.atencion_salud.id }, :method => :post,class: "btn btn-xs btn-warning" %>
          <% elsif agendamiento.estado_id == 10 %> 
            <%= button_to "Continuar", {:controller => :atenciones_salud, :action => 'reabrirAtencion', :id_atencion => agendamiento.atencion_salud.id }, :method => :post,class: "btn btn-xs btn-primary" %> 
          <% elsif existeAtencion(agendamiento.id) %>
            <%= button_to "Continuar", {:controller => :atenciones_salud, :action => 'editarAtencion', :id => agendamiento.atencion_salud.id  }, :method => :post,class: "btn btn-xs btn-primary" %>
          <% elsif agendamiento.estado_id == 5 %>    
            <%= button_to "Atender paciente", {:controller => :atenciones_salud,
            :action => 'crearAtencion', :id => agendamiento.id }, :method => :post,class: "btn btn-xs btn-success" %>
          <% elsif agendamiento.estado_id == 2 %>
            <button id="agen<%= agendamiento.id%>" type="button" class="btn btn-xs btn-warning" onclick="desbloquearHoraAgen(<%= agendamiento.id%>)">Desbloquear Hora</button>  
          <% elsif agendamiento.estado_id == 1 %>  
            <button id="agen<%= agendamiento.id%>" type="button" class="btn btn-xs btn-default" onclick="bloquearHoraAgen(<%= agendamiento.id%>)">Bloquear Hora</button>     
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>   
    
  <% end %> 
</div>

app/views/home/_inicio.html.erb
<div class='container'>
	<div class='row'><h4>Inicio</h4>
		<div class='col-md-12 column'>
			<h4>Horas agendadas</h4>
			<% if @horas_agendadas.empty? %>	  		
  			No hay horas agendadas.
  		<% else %>
	  		<table id="lista_agendamientos" class="table table-striped table-bordered display compact" cellspacing="0" width="100%">
			    <thead>
			      <tr>
			        <th>Fecha</th>
			        <th>Lugar</th>
			        <th>Profesional</th>
			        <th>Especialidad</th>
			        <th>Paciente</th>
			        <th>Pidió la hora</th>         
			        <th>Ver</th>         
			      </tr>
			    </thead>
			    <tbody>      
			      <% @horas_agendadas.each do |hora_agendada| %>
			        <tr>
			          <td><%= hora_agendada.fecha_comienzo.strftime("%Y-%m-%d %H:%M") %></td>
			          <td><%= hora_agendada.especialidad_prestador_profesional.prestador.nombre %></td>
			          <td><%= hora_agendada.especialidad_prestador_profesional.profesional.showName('%n%p%m') %></td> 
			          <td><%= hora_agendada.especialidad_prestador_profesional.especialidad.nombre %></td>
			          <td><%= hora_agendada.persona.showName('%n%p%m') %></td>
			          <td><%= hora_agendada.quien_pide_hora.showName('%n%p%m') %></td> 			                     
			       		<td><a href="#" onclick="cargarDetalleAgend(<%= hora_agendada.id %>)" >Ver</a></td>
			        </tr>
			      <% end %>  
			    </tbody>
			  </table>
  		<% end %>
		</div>		
	</div>
	<div class='row'>
		<div class='col-md-12 column'>
			<h4>Atenciones de salud</h4>
			<% if @atenciones_realizadas.empty? %>	  		
  			No hay atenciones de salud realizadas.
  		<% else %>
	  		<table id="lista_atenciones_realizadas" class="table table-striped table-bordered display compact" cellspacing="0" width="100%">
			    <thead>
			      <tr>
			        <th>Fecha</th>
			        <th>Lugar</th>
			        <th>Profesional</th>
			        <th>Especialidad</th>
			        <th>Paciente</th>       
			        <th>Ver</th>         
			      </tr>
			    </thead>
			    <tbody>      
			      <% @atenciones_realizadas.each do |atencion_realizada| %>
			        <tr>
			          <td><%= atencion_realizada.agendamiento.fecha_comienzo.strftime("%Y-%m-%d %H:%M") %></td>
			          <td><%= atencion_realizada.agendamiento.especialidad_prestador_profesional.prestador.nombre %></td>
			          <td><%= atencion_realizada.agendamiento.especialidad_prestador_profesional.profesional.showName('%n%p%m') %></td> 
			          <td><%= atencion_realizada.agendamiento.especialidad_prestador_profesional.especialidad.nombre %></td>
			          <td><%= atencion_realizada.agendamiento.persona.showName('%n%p%m') %></td>			                     
			       		<td><%= link_to 'Ver atención', atenciones_salud_path(atencion_realizada.id) %></td>
			        </tr>
			      <% end %>  
			    </tbody>
			  </table>
  		<% end %>
		</div>		
	</div>
</div>

<div class="modal fade" id="modal-container-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg3">
    <div class="modal-content" id="modal-content-1"></div>          
  </div>        
</div> 


<%= javascript_include_tag "home" %>	

app/views/home/_inicio_agendamiento.html.erb
<div class='container'>
	<div class='row'><h4>Últimas acciones</h4>
		<% if tieneRol('Generar agendamientos') %>
	  	<div id="acciones_masivas_div">
	  		<% unless @acciones_masivas.empty? %>
	  			<%= button_to "Actualizar", root_path, :method => :get, class: "btn btn-xs btn-success" %><br><br>
	  		<% end %>
	  		<table class="table table-striped table-hover table-condensed">
				  <thead>
				    <tr class="info">
				    	<th class="col-sm-1">Tipo</th>
				    	<th class="col-sm-1">Fecha</th>
				    	<th class="col-sm-1">Profesional</th>
				    	<th class="col-sm-1">Especialidad</th>
				    	<th class="col-sm-1">Agendamientos</th>
				    	<th class="col-sm-1">Eliminados</th>
				    	<th class="col-sm-1">Acción</th>
				    </tr>
				  </thead>
				  <tbody id='acciones_masivas_body'>
				  	<% if @acciones_masivas.empty? %>
				  		<tr id='tr-vacio-acciones-masivas'><td colspan='7'>No se han realizado acciones aún.</td></tr>
    				<% else %> 
			  			<% @acciones_masivas.each do |accion_masiva| %>			  		     
			  				<%= render :partial => "agendamiento/accion_masiva", :locals => {:accion_masiva => accion_masiva } %>
			  			<% end %>
			  		<% end %>
			  	</tbody>    
				</table>
	  	</div>
	  <% end %>	
	</div>
</div>

app/views/home/_log_actualizaciones.html.erb
<div id="log-actualizaciones">
  <h4>Últimas actualizaciones de horas</h4>
    <% if @actualizaciones[0].nil? %>
      No hay actualizaciones de horas que mostrar.
    <% else %>

      <table class="table table-striped table-hover table-condensed">
        <thead class="ajust-head">
          <tr class="info"><th class="col-sm-1">Hora de modificación</th><th class="col-sm-1">Evento</th><th class="col-sm-2">Modificado por</th><th class="col-sm-1">Hora de la atención</th><th class="col-sm-2">Paciente de la atención</th></tr>
        </thead>
        <tbody>   
          <% @actualizaciones.each do |actualizacion| %>
            <tr>
              <td><%= actualizacion.fecha.to_s(:time) %></td>
              <td><%= actualizacion.agendamiento_estado.nombre %></td> 
              <td><%= actualizacion.responsable.showName('%n%p%m') %> </td>
              <td><%= actualizacion.fecha_comienzo ? actualizacion.fecha_comienzo.to_s(:time) : 'No agendada' %></td>     
              <td><%= actualizacion.persona_id ? PerPersonas.find(actualizacion.persona_id).showName('%n%p%m') : '-' %> </td> 
            </tr>
          <% end %>                
        </tbody>
      </table>

    <% end %>

</div>

app/views/home/_proximos_pacientes.html.erb

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Próximas atenciones agendadas</h3>
  </div>
  <div class="panel-body">
    <table class="table table-striped table-bordered table-hover table-condensed">
      <thead>
        <tr><th>Paciente</th><th>Hora de atención</th></tr>
      </thead>
      <tbody>
      

      </tbody>
    </table>
   
  </div>
  <div class="panel-footer">
    Panel footer
  </div>
</div>


app/views/home/about.html.erb
<h3>About us</h3>

app/views/home/account_created.html.erb
<h3>Tu cuenta ha sido creada</h3>
<p>Hemos enviado un correo de confirmación al correo electrónico ingresado para finalizar el registro.</p>

app/views/home/actualizarAtenciones.js.erb
$( "#horas-agendadas" ).replaceWith("<%= escape_javascript( render :partial => "horas_agendadas", :locals => {:agendamientos => @agendamientos} ) %>")
$( "#log-actualizaciones" ).replaceWith("<%= escape_javascript( render :partial => "log_actualizaciones", :locals => {:actualizaciones => @actualizaciones} ) %>")

app/views/home/index_agendamiento.html.erb
<div class="container menu-inicial">
	<div class="row clearfix">
		<div class="col-md-2 column">
			<ul id="nav-antecedentes" class="nav nav-pills nav-pills nav-stacked nav-antecedentes" role="tablist">
				<li class="active"><a href="#inicio" role="tab" data-toggle="tab">Inicio</a></li>				
				<% if tieneRol('Confirmar agendamientos') or tieneRol('Recibir pacientes') or tieneRol('Bloquear horas') or tieneRol('Tomar horas') %>
					<li><a href="#agenda" role="tab" data-toggle="tab">Ver agenda</a></li>
				<% end %>		
				<% if tieneRol('Generar agendamientos') %>
			  	<li><a href="#ant_med" role="tab" data-toggle="tab">Agregar horas</a></li>
			  <% end %>	
			  <% if tieneRol('Generar estadísticas') %>
			  	<li><a href="#gen_boletas" role="tab" data-toggle="tab">Generar boletas</a></li>
			  	<li><a href="#ver_boletas" role="tab" data-toggle="tab">Ver boletas</a></li>
			  <% end %>		  
			</ul>
		</div>
		<div class="col-md-10 column">
			<div class="tab-content tab-inicial">
				<div class="tab-pane active" id="inicio"><%= render :partial => "inicio_agendamiento" %></div>
				<% if tieneRol('Confirmar agendamientos') or tieneRol('Recibir pacientes') or tieneRol('Bloquear horas') or tieneRol('Tomar horas') %>
					<div class="tab-pane" id="agenda"><%= render :partial => "agendamiento/buscador_hora" %></div>
				<% end %>	
				<% if tieneRol('Generar agendamientos') %>
			  	<div class="tab-pane" id="ant_med"><%= render :template => "agendamiento/showFormBusqueda", :locals => {:especialidades => @especialidades , :profesionales => @profesionales } %></div>
			  <% end %>
			  <% if tieneRol('Generar estadísticas') %>
			  	<div class="tab-pane" id="gen_boletas"><%= render :template => "administracion/generar_boletas" %></div>
			  	<div class="tab-pane" id="ver_boletas"><%= render :template => "administracion/ver_boletas" %></div>
			  <% end %>					  
			</div>
		</div>
	</div>
</div>

app/views/home/index_profesional.html.erb
<div class="container menu-inicial">
	<div class="row clearfix">
		<div class="col-md-3 column">
			<ul id="nav-antecedentes" class="nav nav-pills nav-pills nav-stacked nav-antecedentes" role="tablist">
			  <li class="active"><a href="#ant_med" role="tab" data-toggle="tab">Horas agendadas para el día</a></li>
			  <li><a href="#ant_quir" role="tab" data-toggle="tab">Últimas actualizaciones</a></li>
			  <li><a href="#agenda" role="tab" data-toggle="tab">Ver agenda</a></li>
			  <li><a href="#atenciones" role="tab" data-toggle="tab">Ver últimas atenciones</a></li>
			  <li><a href="#atenciones_realizadas" role="tab" data-toggle="tab">Buscar atenciones realizadas</a></li>
			  <li><a href="#atenciones_para_pago" role="tab" data-toggle="tab">Ver atenciones para pago</a></li>
			  <li><a href="#boletas" role="tab" data-toggle="tab">Ver boletas</a></li>
			</ul>
		</div>
		<div class="col-md-9 column">
			<div class="tab-content tab-inicial">
			  <div class="tab-pane active" id="ant_med"><%= render :partial => "horas_agendadas", :locals => {:agendamientos => @agendamientos} %></div>
			  <div class="tab-pane" id="ant_quir"><%= render :partial => "log_actualizaciones", :locals => {:actualizaciones => @actualizaciones} %> <button id="actualizar" class="btn btn-success has-spinner"><span class="spinner"><i class="fa fa-refresh fa-spin"></i></span>Actualizar atenciones</button></div>
			  <div class="tab-pane" id="agenda"><%= render :partial => "agendamiento/buscador_hora" %></div>
			  <div class="tab-pane" id="atenciones"><%= render :partial => "atenciones_salud/index" %></div>
				<div class="tab-pane" id="atenciones_realizadas"><%= render :partial => "atenciones_salud/index_buscar" %></div>
				<div class="tab-pane" id="atenciones_para_pago"><%= render :partial => "administracion/atenciones_para_pago" %></div>
				<div class="tab-pane" id="boletas"><%= render :partial => "administracion/boletas" %></div>
			</div>
		</div>
	</div>
</div>

<%= javascript_include_tag "home" %>
<%= javascript_include_tag "administracion" %>
<%= javascript_include_tag "label_better" %> 

app/views/home/password_reset.html.erb
<h3>Recuperación de contraseña</h3>
<p>Hemos enviado un correo de confirmación al correo electrónico ingresado para recuperar tu contraseña.</p>

app/views/home/password_reseted.html.erb
<h3>Contraseña modificada</h3>
<p>Tu contraseña se ha modificado. Ahora puedes ingresar a <%= link_to "MedRacer", root_path %></p>